# @package _group_
- _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${general.project_name}

- _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${general.save_dir}
  name: ${general.experiment_id}
  version: ${general.version}
